services:
  db:
    image: postgres:15
    container_name: signvision-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.docker
    networks:
      - signvision-network
    ports:
      - "8091:5432"
  web:
    build: .
    container_name: signvision-web
    volumes:
      - .:/code
    ports:
      - "8090:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - signvision-network

networks:
  signvision-network:
    name: signvision-network