# Generated by Django 4.2.4 on 2023-08-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signvision_core', '0003_alter_signlanguage_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesture',
            name='hands',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], default='both'),
        ),
    ]
