# Generated by Django 4.2.4 on 2023-08-13 13:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signvision_core', '0004_alter_gesture_hands'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('WRIST', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('THUMB_BASE', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('THUMB_TIP', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('INDEX_BASE', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('INDEX_TIP', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('MIDDLE_BASE', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('MIDDLE_TIP', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('RING_BASE', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('RING_TIP', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('PINKY_BASE', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('PINKY_TIP', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('gesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='signvision_core.gesture')),
            ],
            options={
                'db_table': 'gesture_data_entries',
            },
        ),
    ]
