# Generated by Django 4.2.4 on 2023-08-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signvision_core', '0005_gestureentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestureentry',
            name='frame_count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
