# Generated by Django 4.2.4 on 2023-08-13 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signvision_core', '0007_alter_gestureentry_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestureentry',
            name='MOUTH',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='entry_type',
            field=models.CharField(choices=[('mediapipe_video', 'Mediapipe Video'), ('unknown', 'Unknown')], default='unknown'),
        ),
    ]
