# Generated by Django 4.2.4 on 2023-08-13 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signvision_core', '0009_rename_index_base_gestureentry_left_index_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_INDEX_BASE',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_INDEX_TIP',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_MIDDLE_BASE',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_MIDDLE_TIP',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_PINKY_BASE',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_PINKY_TIP',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_RING_BASE',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_RING_TIP',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_THUMB_BASE',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_THUMB_TIP',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestureentry',
            name='RIGHT_WRIST',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
