# Generated by Django 4.2.4 on 2023-08-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signvision_core', '0010_gestureentry_right_index_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestureentry',
            name='gesture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='signvision_core.gesture'),
        ),
    ]
